CREATE TABLE IF NOT EXISTS confessions (
    id VARCHAR(255) PRIMARY KEY,
    content VARCHAR(800) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    NSFW BOOLEAN DEFAULT FALSE,
    category VARCHAR(20) DEFAULT 'Other',
    is_reviewed BOOLEAN DEFAULT FALSE,
    is_approved BOOLEAN DEFAULT FALSE,
    is_read BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(255) PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '1 day'
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    twitch_id VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE EXTENSION IF NOT EXISTS pg_cron;
